export const GAMES = [
  {
    slug: 'spy',
    accent: 'var(--color-spy)',
    icon: '/game-icons/spy.webp',
    title: 'Шпион',
    desc: 'Один игрок не знает секретную локацию или персонажа — остальные знают и должны вычислить шпиона по разговору.',
    meta: 'от 3 игроков · онлайн',
  },
  {
    slug: 'mission',
    accent: 'var(--color-mission)',
    icon: '/game-icons/mission.webp',
    title: 'Тайная миссия',
    desc: 'У каждого своя смешная секретная задача на раунд — выполни её незаметно во время обычного разговора, а потом угадай чужие.',
    meta: 'от 3 игроков · онлайн',
  },
  {
    slug: 'codenames',
    accent: 'var(--color-codenames)',
    icon: '/game-icons/codenames.webp',
    title: 'Кодовые имена',
    desc: 'Командная игра на подсказки одним словом — угадайте все свои карточки на поле раньше соперников.',
    meta: 'от 4 игроков · 2 команды',
  },
  {
    slug: 'mafia',
    accent: 'var(--color-mafia)',
    icon: '/game-icons/mafia.webp',
    title: 'Мафия',
    desc: 'Ночью мафия тайно выбирает жертву, днём город обсуждает и голосует, кому не доверять. Есть шериф и доктор.',
    meta: 'от 4 игроков · роли и голосование',
  },
  {
    slug: 'wavelength',
    accent: 'var(--color-wavelength)',
    icon: '/game-icons/wavelength.webp',
    title: 'Волна',
    desc: 'Капитан даёт подсказку, где на скрытой шкале спряталась точка — команда угадывает позицию слайдером. Чем точнее, тем больше очков.',
    meta: 'от 4 игроков · 2 команды',
  },
  {
    slug: 'whoami',
    accent: 'var(--color-whoami)',
    icon: '/game-icons/whoami.webp',
    title: 'Кто я?',
    desc: 'Все видят вашу секретную личность, кроме вас самих — угадайте её вопросами вслух быстрее остальных.',
    meta: 'от 3 игроков · онлайн',
  },
  {
    slug: 'nardy',
    accent: 'var(--color-nardy)',
    icon: '/game-icons/nardy.webp',
    title: 'Длинные нарды',
    desc: 'Классические длинные нарды один на один — кости, выход шашек, марс и удваивающий куб. Без взятия шашек соперника.',
    meta: '2 игрока · онлайн',
  },
  {
    slug: 'categories',
    accent: 'var(--color-categories)',
    icon: '/game-icons/categories.webp',
    title: 'Категории',
    desc: 'Буква и 5 категорий — на скорость придумайте слова, начинающиеся на неё. Очки за уникальные ответы считаются автоматически.',
    meta: 'от 2 игроков · онлайн',
  },
  {
    slug: 'skuf',
    accent: 'var(--color-skuf)',
    icon: '/game-icons/skuf.webp',
    title: 'Скуф ищет альтушку',
    desc: 'Несколько ночей тайной переписки и свиданий — у каждого своя секретная роль, которая незаметно влияет на очки. Развязка непредсказуема.',
    meta: 'от 3 игроков · онлайн',
  },
]
